### ISSUE TITLE
Call Node's process.binding() in RegisterModule()

### ISSUE THREAD

**Issue by justus-hildebrand** [hpicgs/node#26]
this enables us to bind native C++ modules in node without having to load a script. Was previously called at the beginning of (for example) our rss_feed JS part.

**Comment by Hannes01071995** [comment]
Brilliant idea!
However, i would suggest that we offer an additional parameter for the `RegisterModule` function, which allows just that behavior. Otherwise the "black magic" could lead to confusion for our future users.
