### ISSUE TITLE
Prepare contacting node devs/community

### ISSUE THREAD

**Issue by cmfcmf** [hpicgs/node#3]
- [x] summarize problem description and api draft
- [x] provide working, building sample code and project
- [x] find best channel to contact devs/community

**Comment by emberflare** [comment]
As described by the [Node Contributing Guide](https://github.com/nodejs/node/blob/master/doc/guides/contributing/pull-requests.md), I think a simple pull request (once we fix tests/style guide/lint and are satisfied with the feature set) might be enough.
