### ISSUE TITLE
bootstrap_node.js: Make reading from stdin configurable

### ISSUE THREAD

**Issue by cmfcmf** [hpicgs/node#34]
Currently, Node.js is hacked to never read from stdin:
https://github.com/hpicgs/node/blob/734d0d6e561a33acfb9ac3b8b4c869f8fb5aa479/lib/internal/bootstrap_node.js#L200-L210

Add a command line parameter (?) to toggle this behaviour.

**Comment by justus-hildebrand** [comment]
Are we keeping stdin-reading for any other reason than backwards compatibility (old ```Start()``` behaviour)? Can't think of one right now.

Should we decide to not allow stdin (making us not perfectly backwards compatible, should still be considered though IMO), we could use the preprocessor flag ```NODE_SHARED_MODE``` to only include the change made in 734d0d6 when building as a shared lib

**Comment by justus-hildebrand** [comment]
current point of discussion: do we want to add a way to query whether node is running as a library or as a native app? If so, how? Environment variable? JS getter function? Another way I have not thought of? (will add decision once it was made)

**Comment by justus-hildebrand** [comment]
did not go with env-variable mentioned earlier, instead gave direct control over wether to spawn REPL or not
